version: '3'

services:
        mysql-development:
                restart: always
                container_name: mysql-development
                image: mysql:8.0.17
                environment:
                        MYSQL_ROOT_PASSWORD: helloworld
                        MYSQL_DATABASE: testapp
                ports:
                        - "3308:3306"
        
        myapp:
                restart: on-failure
                build: ./backend/
                expose:
                        - "8115"
                ports:
                        - 8115:8115
                environment:
                        WAIT_HOSTS: mysql:3306
                depends_on:
                        - mysql-development

        frontend: 
                build: ./frontend
                command: npm run docker
                volumes: 
                        - ./frontend:/usr/src/app
                working_dir: /usr/src/app
                ports: 
                        - "3000:3000"
                environment: 
                        HOST: 0.0.0.0
